[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "../lexer" }
thiserror = { workspace = true }
miette = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
